### ISSUE TITLE
No unit tests in the unit test poject

### ISSUE THREAD

**Issue by apryiomka** [vhrobles/NET-Core--EF7-with-Angular#1]
Would you come up with a couple of test scenarios for controllers and services? Login test doesn't test anything.

**Comment by vhrobles** [comment]
Hi Alex! Thanks for taking time to review my code. I didn't have enough time to write unit tests since I'm fairly new with this new version of the framework and I was having difficulties to make it work with new version of Moq, but I could certainly try to write a couple :)

**Comment by apryiomka** [comment]
I didn't realized this, but .Net core was officially released today (I am still on RC2 :)). I would guess it should work better now. I haven't checked the Moq lib though, it seems to be still in alpha. Fill free to skip Moq lib altogether and just do "manual mocking" with some fake classes :) :).

**Comment by vhrobles** [comment]
Sounds good! I will do that!

**Comment by vhrobles** [comment]
Hi Alex, I've added a couple of UT's in a new project. I couldn't make the test runner work for xunit in the new framework so I've created a new test project

**Comment by apryiomka** [comment]
Thanks for updating the code, looks good!
